apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: metadata
configMapGenerator:
- name: metadata-db-parameters
<<<<<<< HEAD
  env: params.env
secretGenerator:
- name: metadata-db-secrets
  env: secrets.env
=======
  envs:
  - params.env
secretGenerator:
- name: metadata-db-secrets
  envs:
  - secrets.env
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
bases:
- ../../base
patchesStrategicMerge:
- metadata-deployment.yaml