apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: serving-cert
spec:
  commonName: kfserving-webhook-server-service.kubeflow.svc
  dnsNames:
  - kfserving-webhook-server-service.kubeflow.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kfserving-webhook-server-cert