apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- config-map.yaml
configMapGenerator:
- name: pipeline-external-mysql-parameters
<<<<<<< HEAD
  env: params.env
=======
  envs:
  - params.env
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: mysqlHost
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlHost
- name: mysqlUser
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlUser
- name: mysqlPassword
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlPassword
configurations:
- params.yaml