apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonLabels:
<<<<<<< HEAD
  app.kubernetes.io/name: pytorch-operator
  app.kubernetes.io/instance: pytorch-operator-v1.0.0
  app.kubernetes.io/version: v1.0.0
=======
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
  app.kubernetes.io/component: pytorch
  app.kubernetes.io/name: pytorch-operator
kind: Kustomization
resources:
- application.yaml
