apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    control-plane: kubeflow
    istio-injection: enabled
<<<<<<< HEAD
=======
    katib-metricscollector-injection: enabled
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
<<<<<<< HEAD
  labels:
    control-plane: kubeflow
=======
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
