apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonLabels:
<<<<<<< HEAD
  app.kubernetes.io/name: aws-alb-ingress-controller
  app.kubernetes.io/instance: aws-alb-ingress-controller-v1.0.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: aws-alb-ingress-controller
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0

=======
  app.kubernetes.io/component: aws-alb-ingress-controller
  app.kubernetes.io/name: aws-alb-ingress-controller
kind: Kustomization
resources:
- application.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
