apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonLabels:
<<<<<<< HEAD
  app.kubernetes.io/name: cloud-endpoints
  app.kubernetes.io/instance: cloud-endpoints-v1.0.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: cloud-endpoints
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0
=======
  app.kubernetes.io/component: cloud-endpoints
  app.kubernetes.io/name: cloud-endpoints
kind: Kustomization
namespace: kubeflow
resources:
- application.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
