---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    autoscaling.knative.dev/metric-provider: custom-metrics
<<<<<<< HEAD
    serving.knative.dev/release: "v0.11.1"
=======
    serving.knative.dev/release: "v0.11.2"
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
  name: custom-metrics-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: knative-serving
