apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    notebook: controller
    name: notebook-controller-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      notebook: controller
  template:
    metadata:
<<<<<<< HEAD
      name: notebook-controller
      labels:
        notebook: controller
    spec:
      containers:
      - name: notebook-controller
        image: tmaxcloudck/notebook-controller-go:b0.0.2
=======
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: manager
        image: gcr.io/kubeflow-images-public/notebook-controller:v20190614-v0-160-g386f2749-e3b0c4
        command:
          - /manager
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      serviceAccountName: service-account
